apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  hosts:
  - "*"
  gateways:
  - httpbin-gateway
  http:   
  - route:
    - destination:
        host: httpbin.default.svc.cluster.local
  timeout: 5s
