apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: checkversion
spec:
  match: destination.labels["app"] == "httpbin"
  actions:
  - handler: chaos.listchecker
    instances:
    - version.listentry
