apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: stdio
spec:
  actions:
  - handler: handler.stdio
    instances:
    - sleep-log.logentry
  match: context.protocol == "http" && sourceLable["app"] == "sleep"
