apiVersion: "config.istio.io/v1alpha2"
kind: memquota
metadata:
  name: handler
spec:
  quotas:
  - name: dest-quota.quota.default
    maxAmount: 20
    validDuration: 10s
    overrides:
    - dimensions:
        destination: httpbin
      maxAmount: 1
      validDuration: 5s
